### ISSUE TITLE
Broken test for definition of INT_FAST24_MAX macro (and isomorphic variants for uint  and other widths).

### ISSUE THREAD

**Issue by mjs-arm** [ARMmbed/nanostack-libservice#44]
The logic tests the presence of:

INT24_FAST_MAX

and defines the presence of:

INT_FAST24_MAX

They should be the same, the latter is correct.

**Comment by kjbracey-arm** [comment]
Whoops. 

Don't suppose you've actually found a system with real 24-bit types have you? Always seemed like an obvious optimisation thing for at least C99 compilers for 8-bit systems to provide. Guess the implementation cost versus benefit ratio isn't brilliant though.
