### ISSUE TITLE
Comparison between signed and unsigned integer expressions

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/nanostack-libservice#61]
https://github.com/ARMmbed/nanostack-libservice/blob/854505d0191e428c07eb25fc9630dc05b21d5a47/source/nsdynmemLIB/nsdynmemLIB.c#L240

https://github.com/ARMmbed/nanostack-libservice/blob/854505d0191e428c07eb25fc9630dc05b21d5a47/source/nsdynmemLIB/nsdynmemLIB.c#L382

**Comment by korjaa** [comment]
Getting this with
`mbed compile -m K64F -t GCC_ARM --profile=mbed-os/tools/profiles/debug.json`

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3201

**Comment by kjbracey-arm** [comment]
Fixed.
